services:
  kali:
    container_name: kali
    image: kalilinux/kali-rolling
    tty: true
    stdin_open: true
    environment:
      - TZ=America/New_York
    cap_add:
      - NET_ADMIN
    #ports: # not required when using a MACVLAN
    networks:
      macvlan255:
        ipv4_address: 10.0.255.150
    #volumes:
    restart: unless-stopped

networks:
  macvlan255:
    name: macvlan255
    external: true
