services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7e"
      DISK_SIZE: "10G"
      CPU_CORES: "4"
      RAM_SIZE: "4G"
      DHCP: "Y" # required for DHCP
      TZ: "US/New_York"            
    device_cgroup_rules: # required for DHCP
      - 'c *:* rwm' # required for DHCP
    devices:
      - /dev/kvm
      - /dev/net/tun
      - /dev/vhost-net # required for DHCP
    cap_add:
      - NET_ADMIN
    #ports: # defining ports is not required when using a macvlan
    #  - 8006:8006
    #  - 3389:3389/tcp
    #  - 3389:3389/udp
    stop_grace_period: 2m
    volumes:
      - windows:/storage
      #- /home/devusr/:/shared
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wod.rule=Host(`wod.home.youngsecurity.net`) || Host(`wod.youngsecurity.net`)"
      - "traefik.http.routers.wod.entrypoints=websecure"
      - "traefik.http.routers.wod.tls=true"
      - "traefik.http.routers.wod.tls.certresolver=cloudflare"
      - "traefik.http.services.wod.loadbalancer.server.port=8006"
    restart: unless-stopped

    networks:
      proxy:
        aliases:
          - windows-proxy
        ipv4_address: 172.18.0.3
      macvlan255:
        aliases:
          - windows-macvlan255
        ipv4_address: 10.0.255.154
    deploy: # required for GPU assignment
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]

networks:
  proxy:
    name: proxy
    external: true
    ipam:
      config:
        - subnet: "172.18.0.0/16"
          gateway: 172.18.0.1
  macvlan255:
    name: macvlan255
    external: true
    ipam:
      config:
        - subnet: "10.0.255.0/24"
          gateway: 10.0.255.1

volumes:
  windows:
    external: true